name: pdist_aggregation
channels:
  - conda-forge
dependencies:
  - python=3.9
  - compilers
  - jupyter
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - scikit-learn-intelex
  - pyaml
  - pip
  - threadpoolctl
  - pre-commit
  - pytest
  - memory_profiler
  - pip:
      # Install cython 3 from upstream directly
      - -e git+https://github.com/cython/cython.git#egg=cython
      # Install fork of scikit-learn containing new implementations
      - -e git+https://github.com/jjerphan/scikit-learn.git@pairwise_aggregation_cython-radius#egg=scikit-learn
      # Install pdist_agregation from source
      - -e ./src
