name: pdist_agregation
channels:
  - conda-forge
dependencies:
  - jupyter
  - numpy
  - cython
  - matplotlib
  - seaborn
  - pandas
  - scikit-learn-intelex
  - pyaml
  - pip
  - pip:
      - --pre
      - --index-url https://pypi.anaconda.org/scipy-wheels-nightly/simple
      - scikit-learn
      # Install pdist_agregation from source
      - -v -e ./src
      # Install cython 3 from upstream directly
      - -v -e git+https://github.com/cython/cython.git#egg=cython
