name: pdist_agregation
channels:
  - conda-forge
dependencies:
  - jupyter
  - numpy
  - cython
  - matplotlib
  - seaborn
  - pandas
  - scikit-learn-intelex
  - pip
  - pip:
      - --pre
      - --index-url https://pypi.anaconda.org/scipy-wheels-nightly/simple
      - scikit-learn
      # pdist_agregation
      - -e ./src
