estimators:
  - name: sklearn
    estimator: sklearn.neighbors.NearestNeighbors
    chunk: False
  - name: daal4py
    estimator: daal4py.sklearn.neighbors.NearestNeighbors
    chunk: False
  - name: new_implementation
    estimator: nn_implementation.NearestNeighbors
    chunk: True
datasets:
  - n_samples_train: 1e6
    n_samples_test: 1e3
    n_features: 1e2
  - n_samples_train: 1e6
    n_samples_test: 1e3
    n_features: 2
chunk_sizes:
  - 128
  - 256
  - 512
  - 1024
  - 2048
  - 4096
  - 8192
