estimators:
  - name: sklearn
    estimator: sklearn.neighbors.NearestNeighbors
    chunk: False
  - name: daal4py
    estimator: daal4py.sklearn.neighbors.NearestNeighbors
    chunk: False
  - name: parallel_knn
    estimator: nn.NearestNeighbors
    chunk: True
datasets:
  - n_samples_train: 1e6
    n_samples_test: 1e3
    n_features: 50
  - n_samples_train: 1e6
    n_samples_test: 1e3
    n_features: 1e2
  - n_samples_train: 1e6
    n_samples_test: 1e3
    n_features: 10e
chunk_sizes:
  - 4096
n_neighbors:
  - 1
  - 10
  - 100
