estimators:
  - name: sklearn
    estimator: sklearn.neighbors.NearestNeighbors
    chunk: False
  - name: daal4py
    estimator: daal4py.sklearn.neighbors.NearestNeighbors
    chunk: False
  - name: "Parallel on X_train"
    estimator: nn.NearestNeighborsParrallelXtrain
    chunk: True
  - name: "Parallel on X_test"
    estimator: nn.NearestNeighborsParrallelXtest
    chunk: True

n_trials: 1

datasets:
  # Motives: a few query point < 256 (observed robust chunk size)
  - n_samples_train: 1e6
    n_samples_test: 1
    n_features: 100
  - n_samples_train: 1e6
    n_samples_test: 50
    n_features: 100
  - n_samples_train: 1e6
    n_samples_test: 256
    n_features: 100

  # Motives: Intermediate datasets
  - n_samples_train: 1e5
    n_samples_test: 1e3
    n_features: 100
  - n_samples_train: 1e5
    n_samples_test: 1e3
    n_features: 500
  - n_samples_train: 1e3
    n_samples_test: 1e5
    n_features: 100
  - n_samples_train: 1e3
    n_samples_test: 1e5
    n_features: 500

chunk_size: # [2 ** i for i in range(6, 13)]
  - 64
  - 128
  - 256
  - 512
  - 1024
  - 2048
  - 4096

n_neighbors:
  - 10
