estimators:
  - name: sklearn
    estimator: sklearn.neighbors.NearestNeighbors
    chunk: False
  - name: daal4py
    estimator: daal4py.sklearn.neighbors.NearestNeighbors
    chunk: False
  - name: "New (single chunking)"
    estimator: nn.NearestNeighborsSingleChunking
    chunk: True
  - name: "New (double chunking)"
    estimator: nn.NearestNeighborsDoubleChunking
    chunk: True

datasets:
  # X_train taller
  - n_samples_train: 1e6
    n_samples_test: 1e3
    n_features: 50
  - n_samples_train: 1e6
    n_samples_test: 1e3
    n_features: 1e2
  - n_samples_train: 1e3
    n_samples_test: 1e1
    n_features: 500

  # X_test taller
  - n_samples_train: 1e3
    n_samples_test: 1e6
    n_features: 50
  - n_samples_train: 1e3
    n_samples_test: 1e6
    n_features: 1e2

working_memories: # [2 ** i for i in range(13, 26, 2)
  - 8192
  - 32768
  - 131072
  - 524288
  - 2097152
  - 8388608
  - 33554432

n_neighbors:
  - 10
