estimators:
  - name: sklearn
    estimator: sklearn.neighbors.NearestNeighbors
    chunk: False
  - name: daal4py
    estimator: daal4py.sklearn.neighbors.NearestNeighbors
    chunk: False
  - name: "New"
    estimator: nn.NearestNeighbors
    chunk: True

datasets:
  # X_train taller
  - n_samples_train: 1e6
    n_samples_test: 1e3
    n_features: 50
  - n_samples_train: 1e6
    n_samples_test: 1e3
    n_features: 1e2
  - n_samples_train: 1e3
    n_samples_test: 1e1
    n_features: 500

  # X_test taller
  - n_samples_train: 1e3
    n_samples_test: 1e6
    n_features: 50
  - n_samples_train: 1e3
    n_samples_test: 1e6
    n_features: 1e2

working_memories: # in bytes, [2 ** i for i in range(17, 26, 2)] + L3 cache size
  - 131072
  - 524288
  - 2097152
  - 4194304  # typical L3 cache size
  - 8388608
  - 33554432

n_neighbors:
  - 10
