estimators:
  - name: sklearn
    estimator: sklearn.neighbors.NearestNeighbors
    chunk: False
  - name: daal4py
    estimator: daal4py.sklearn.neighbors.NearestNeighbors
    chunk: False
  - name: "New (single chunking)"
    estimator: nn.NearestNeighborsSingleChunking
    chunk: True
  - name: "New (double chunking)"
    estimator: nn.NearestNeighborsDoubleChunking
    chunk: True

datasets:
  # X_train taller
  - n_samples_train: 1e6
    n_samples_test: 1e3
    n_features: 50
  - n_samples_train: 1e6
    n_samples_test: 1e3
    n_features: 1e2
  - n_samples_train: 1e6
    n_samples_test: 1e3
    n_features: 500

  # X_test taller
  - n_samples_train: 1e3
    n_samples_test: 1e6
    n_features: 50
  - n_samples_train: 1e3
    n_samples_test: 1e6
    n_features: 1e2
  - n_samples_train: 1e3
    n_samples_test: 1e6
    n_features: 500

chunk_sizes:
  - 2048
  - 4096
  - 5120
  - 6144
  - 7168
  - 8192
n_neighbors:
  - 1
  - 10
  - 100
