estimators:
  - name: daal4py
    estimator: daal4py.sklearn.neighbors.NearestNeighbors
    chunk: False
  - name: "auto"
    estimator: nn.NearestNeighborsParallelAuto
    chunk: True
  - name: "chunk_on_train"
    estimator: nn.NearestNeighborsParallelXtrain
    chunk: True
  - name: "chunk_on_test"
    estimator: nn.NearestNeighborsParallelXtest
    chunk: True

n_trials: 5

datasets:
  # Motives: a few query point < 256 (observed robust chunk size)
  - n_samples_train: 1e5
    n_samples_test: 1
    n_features: 50
  - n_samples_train: 1e5
    n_samples_test: 128
    n_features: 50
  - n_samples_train: 1e5
    n_samples_test: 256
    n_features: 50
  
  - n_samples_train: 1e5
    n_samples_test: 1
    n_features: 100
  - n_samples_train: 1e5
    n_samples_test: 128
    n_features: 100
  - n_samples_train: 1e5
    n_samples_test: 256
    n_features: 100

  - n_samples_train: 1e5
    n_samples_test: 1
    n_features: 500
  - n_samples_train: 1e5
    n_samples_test: 128
    n_features: 500
  - n_samples_train: 1e5
    n_samples_test: 256
    n_features: 500

  # Motives: Intermediate datasets

  # X_train taller
  - n_samples_train: 1e5
    n_samples_test: 1e3
    n_features: 100
  - n_samples_train: 1e5
    n_samples_test: 1e3
    n_features: 500

  # X_test taller
  - n_samples_train: 1e3
    n_samples_test: 1e5
    n_features: 100
  - n_samples_train: 1e3
    n_samples_test: 1e5
    n_features: 500

chunk_size: # [2 ** i for i in range(6, 13)]
  - 64
  - 128
  - 256
  - 512
  - 1024
  - 2048
  - 4096

n_neighbors:
  - 1
  - 10
  - 100
